# Generated by Django 3.1.3 on 2020-11-12 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('telephone', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Veterinary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('telephone', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], max_length=1)),
                ('age', models.PositiveIntegerField()),
                ('species', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.client')),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('7-8', '7 am - 8 am'), ('8-9', '8 am - 9 am'), ('9-10', '9 am - 10 am'), ('10-11', '10 am - 11 am'), ('11-12', '11 am - 12 pm'), ('12-1', '12 pm - 1 pm'), ('1-2', '1 pm - 2 pm'), ('2-3', '2 pm - 3 pm'), ('3-4', '3 pm - 4 pm'), ('4-5', '4 pm - 5 pm')], max_length=5)),
                ('reason', models.CharField(max_length=30)),
                ('req_date', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.client')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.pet')),
                ('veterinary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.veterinary')),
            ],
        ),
    ]
