# Generated by Django 3.1.3 on 2020-11-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='veterinary',
            name='username',
            field=models.CharField(max_length=10),
        ),
    ]
